services:
  backend_1:
    build:
      context: .  
      dockerfile: Dockerfile  
    restart: always
    container_name: backend_1
    working_dir: /app
    volumes:
      - .:/app  
    ports:
      - "4200:4200"  
    env_file: 
      - .env
    networks:
      - backend_network

  backend_2:
    build:
      context: .  
      dockerfile: Dockerfile  
    restart: always
    container_name: backend_2
    working_dir: /app
    volumes:
      - .:/app  
    ports:
      - "4201:4200"  
    env_file: 
      - .env
    networks:
      - backend_network

  backend_backup:
    build:
      context: .  
      dockerfile: Dockerfile  
    restart: always
    container_name: backend_backup
    working_dir: /app
    volumes:
      - .:/app  
    ports:
      - "4202:4200"  
    env_file: 
      - .env
    networks:
      - backend_network

  nginx:
    build:
      dockerfile: nginx/nginx.dockerfile
      context: .
    image: nginx
    restart: always
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - backend_1
      - backend_2
      - backend_backup
    networks:
      - backend_network

volumes:
  doge_store_back:

networks:
  backend_network:
    driver: bridge
