version: '3.8'

services:
  doge_back:
    build:
      context: .  
      dockerfile: Dockerfile  
    restart: always
    container_name: doge_store_back
    working_dir: /app
    volumes:
      - .:/app  
    ports:
      - "4200:4200"  
    env_file: 
      - .env

volumes:
  doge_store_back:
