services:
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: doge_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80
    volumes:
      - pgadmin_storage:/var/lib/pgadmin
volumes:
  pgadmin_storage:
